// Code generated by goctl. DO NOT EDIT.
// Source: user_score.proto

package userscore

import (
	"context"
	"rpc-common/score"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserScoreRequest  = score.UserScoreRequest
	UserScoreResponse = score.UserScoreResponse

	UserScore interface {
		SaveScore(ctx context.Context, in *UserScoreRequest, opts ...grpc.CallOption) (*UserScoreResponse, error)
		SaveScoreCallback(ctx context.Context, in *UserScoreRequest, opts ...grpc.CallOption) (*UserScoreResponse, error)
	}

	defaultUserScore struct {
		cli zrpc.Client
	}
)

func NewUserScore(cli zrpc.Client) UserScore {
	return &defaultUserScore{
		cli: cli,
	}
}

func (m *defaultUserScore) SaveScore(ctx context.Context, in *UserScoreRequest, opts ...grpc.CallOption) (*UserScoreResponse, error) {
	client := score.NewUserScoreClient(m.cli.Conn())
	return client.SaveScore(ctx, in, opts...)
}

func (m *defaultUserScore) SaveScoreCallback(ctx context.Context, in *UserScoreRequest, opts ...grpc.CallOption) (*UserScoreResponse, error) {
	client := score.NewUserScoreClient(m.cli.Conn())
	return client.SaveScoreCallback(ctx, in, opts...)
}
