// Code generated by goctl. DO NOT EDIT.
// Source: user_score.proto

package server

import (
	"context"
	"rpc-common/user"
	"user/internal/logic"
	"user/internal/svc"

)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user.IdRequest) (*user.UserResponse, error) {
	l := logic.NewUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) Save(ctx context.Context, in *user.UserRequest) (*user.UserResponse, error) {
	l := logic.NewUserLogic(ctx, s.svcCtx)
	return l.SaveUser(in)
}

func (s *UserServer) SaveCallback(ctx context.Context, in *user.UserRequest) (*user.UserResponse, error) {
	l := logic.NewUserLogic(ctx, s.svcCtx)
	return l.SaveCallback(in)
}
