// Code generated by goctl. DO NOT EDIT.
// Source: user_score.proto

package server

import (
	"context"
	"rpc-common/score"

	"user-score/internal/logic"
	"user-score/internal/svc"
)

type UserScoreServer struct {
	svcCtx *svc.ServiceContext
	score.UnimplementedUserScoreServer
}

func NewUserScoreServer(svcCtx *svc.ServiceContext) *UserScoreServer {
	return &UserScoreServer{
		svcCtx: svcCtx,
	}
}

func (s *UserScoreServer) SaveScore(ctx context.Context, in *score.UserScoreRequest) (*score.UserScoreResponse, error) {
	l := logic.NewSaveScoreLogic(ctx, s.svcCtx)
	return l.SaveScore(in)
}

func (s *UserScoreServer) SaveScoreCallback(ctx context.Context, in *score.UserScoreRequest) (*score.UserScoreResponse, error) {
	l := logic.NewSaveScoreCallbackLogic(ctx, s.svcCtx)
	return l.SaveScoreCallback(in)
}
